site_name: MLModule
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
repo_url: https://github.com/LSIR/mlmodule
repo_name: LSIR/mlmodule

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - css/mkdocstring.css

plugins:
  - search
  - bibtex:
      bib_file: "docs/references.bib"
  - markdownextradata
  - mkdocstrings:
      handlers:
        python:
          rendering:
            heading_level: 3
            show_root_heading: true
            show_signature_annotations: true
            show_bases: false
            show_source: false
      watch:
        - src/mlmodule

extra:
  develop:
    python_version: 3.7
    pytorch_version: 1.9
    tox_env_version: py37-pt19
  release:
    tox_env_version: "{py37,py38,py39}{-pt19,-pt110}{-cuda,}"

  models:
    resnet:
      - name: PyTorch ResNet pre-trained on ImageNet
        factory: torch_resnet_imagenet
        training_id: imagenet
    densenet:
      - name: PyTorch DenseNet pre-trained on ImageNet
        factory: torch_densenet_imagenet
        training_id: imagenet
      - name: PyTorch DenseNet pre-trained on Places365
        factory: torch_densenet_places365
        training_id: places365
